### ISSUE TITLE
Commands can be triggered without prefix

### ISSUE THREAD

**Issue by raws** [blolol/rpg#8]
Simply typing "characters" or "c:online" in a channel with Wheaties triggers those RPG commands. For some reason it's not requiring the command prefix.

**Comment by Corgan** [comment]
Is this due to listen_to :message not using the regex prefix that was defined in the cinch plugins?
https://github.com/blolol/rpg/blob/master/app/bots/application_bot.rb#L26
Those hooks run on both match and listen_to.

**Comment by raws** [comment]
I think you're right. When I switched from using `match` to `listen_to`, I totally forgot to start manually checking for the prefix :grinning:
